using AdventOfCode._2024;
using FluentAssertions;

namespace AdventOfCodeTests._2024;

public class Day08Tests
{
    private const string TestInput = @"............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............";

    [Fact]
    public void TestCountAntiNodes()
    {
        Day08.CountAntiNodes(TestInput).Should().Be(14);
    }

    [Fact]
    public void TestCountAntiNodesWithRH()
    {
        Day08.CountAntiNodesWithRH(TestInput).Should().Be(34);
    }
}
